### ISSUE TITLE
add customization in move to next button

### ISSUE THREAD

**Issue by bibek-ranjan-saha** [tiamo/flutter-concentric-transition#13]
### Contextualize the feature
Just like cuberto original design please add customization as we can just add an arrow or image or something

![next button](https://user-images.githubusercontent.com/58353328/167308480-f700aa96-a398-4664-90b1-600f38f40925.png)

### Describe the feature
add an arrow or text or icon in the button to move to next page 

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by tiamo** [comment]
@bibek-ranjan-saha thanks, it would be nice to have.

**Comment by tiamo** [comment]
added in v1.0.2
