### ISSUE TITLE
Content and Colors not displaying properly

### ISSUE THREAD

**Issue by nico671** [tiamo/flutter-concentric-transition#14]
## 🐛 Bug Report

  
I just switched out PageView.builder for ConcentricPageView, and the first page is blank unless you scroll to the next page and come back. The same thing happens with the colors, they are wrong until you go past and then come back to the page.
  ### Expected behavior
Colors and widgets displaying correctly.
  ### Reproduction steps
Switch out PageView.builder for ConcentricPageView
  ### Configuration
None
  **Version:** 1.02

  **Platform:**
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by nico671** [comment]
I don't know if this is important but the content issue is only on the first page and the color issue is only on the second and third (of 3)

**Comment by tiamo** [comment]
@nico671 Thanks, I'll check it out

**Comment by thorgexyz** [comment]
@tiamo Any update on this? And thx for your work!

The bug with the first page being empty was introduced in 1.0.2. Just checked with 1.0.1 and it's working fine. Will use 1.0.1 for now.

**Comment by tiamo** [comment]
@thorgexyz, could you check out the latest version from the master branch?

**Comment by thorgexyz** [comment]
@tiamo works!

thx my guy
