### ISSUE TITLE
I'm getting error: "The minCompileSdk (31) specified in a dependency's AAR metadata...." while compiling example

### ISSUE THREAD

**Issue by saksham-gt** [tiamo/flutter-concentric-transition#15]
##  Bug Report

  As I tried to run the example in Android Phone, it shows me the error:
```The minCompileSdk (31) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)         is greater than this module's compileSdkVersion (android-30). Dependency: androidx.window:window-java:1.0.0-beta04.```

  ### Expected behavior
 Should've compiled without any error

  ### Reproduction steps
 Just run the example on Android Phone

  **Platform:**
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by saksham-gt** [comment]
I found the solution though, just mentioning the `compileSdkVersion` and `targetSdkVersion` to `31` in `app/build.gradle` will do the trick. 
But wanted to make sure if this is an issue just for me or if anyone else is also facing the same issue?

**Comment by tiamo** [comment]
Hi @glitchpop-frenzy, actually it's your internal error or maybe another dependency. The library doesn't use native calls, only dart lang.

**Comment by saksham-gt** [comment]
ohh, okay..thanks.
