### ISSUE TITLE
Next Button Icon Offset

### ISSUE THREAD

**Issue by Crucialjun** [tiamo/flutter-concentric-transition#16]
## 💬 Questions and Help

When using the next button builder the icon is off from the circle, is there a way to ensure that it stays in place , which is in the middle of the circle?

**Comment by tiamo** [comment]
Hi @Crucialjun! Have you tried wrap the icon with "Center" ?

**Comment by Crucialjun** [comment]
Yes I have still doesn't work

**Comment by biswa1751** [comment]
You can Add padding to make it visually center.
