### ISSUE TITLE
Button Color Animation not matched according to design

### ISSUE THREAD

**Issue by biswa1751** [tiamo/flutter-concentric-transition#17]
## 🐛 Bug Report

When we navigate to next page the button color changes instantly.

  ### Expected behavior

According to the design in dribble , after navigating to the next page  button filled with color from  0 to full .

 ![Screenshot 2022-09-06 at 11 19 19 PM](https://user-images.githubusercontent.com/36480889/188704799-3dfa7220-2602-4114-9bf6-fea122caf3c3.png)![Screenshot 2022-09-06 at 11 19 25 PM](https://user-images.githubusercontent.com/36480889/188704788-50219dcf-2ddf-4d82-be5c-2c291c237c4a.png)
  ### Reproduction steps
SImple implementation
  ### Configuration
  **Version:** 1.x
  **Platform:**
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by tiamo** [comment]
@biswa1751, feel free to open a PR as well if you have any suggestions, thanks.
